### ISSUE TITLE
Problems running on FiPy from Pycom

### ISSUE THREAD

**Issue by skuppens** [Notthemarsian/CCS811#2]
Hi,

I'm having trouble getting this library to work with a FiPy by Pycom.
I uploaded the CCS811.py file to the lib folder of the FiPy. Also changed example.py to main.py and uploaded this aswell.
 on reboot i get this:
`ets Jun  8 2016 00:22:57

rst:0x7 (TG0WDT_SYS_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff8028,len:8
load:0x3fff8030,len:2156
ho 0 tail 12 room 4
load:0x4009fa00,len:19208
entry 0x400a05f4
Initializing filesystem as FatFS!
Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "main.py", line 12, in main
ValueError: invalid argument(s) value
Pycom MicroPython 1.20.0.rc13 [v1.9.4-94bb382] on 2019-08-22; FiPy with ESP32
Type "help()" for more information.
>>> `

Any idea how to get this to work? 
I would like to combine this with the LoRAWAN example from PyCom to upload data to TTN.

Thank you for the insight and time,

Stijn

**Comment by skuppens** [comment]
Hi,

Got it to work now, There had to be some changes in the bus addr (now set to 2 instead of 0) of the I2C aswell.

Stijn

**Comment by Notthemarsian** [comment]
Hi,
I haven’t tried a pycom board but nice that someone uses my little library:

the program aborts at line 12, which initialises the I2C bus:

12 i2c = I2C(scl=Pin(5), sda=Pin(4))

With the message: ValueError: invalid argument(s) value

Now, line 12 is standard micropython syntax and uses the pins 4 and 5.

Looks like pycom has deviated from standard micropython here:
On
https://docs.pycom.io/firmwareapi/pycom/machine/i2c/

I find the following syntax, which is slightly different:


i2c = I2C(0, I2C.MASTER)

Try this. If you get more errors I’m afraid you will have to check each
time if there is a difference in syntax between pycom and standard
micropython.

I wasn’t really happy with my sensor in the end. It seemed to work for a
while, then started to drift towards very high readings. I might try a
infrared sensor next but they are more expensive........

Have fun, Patrick

**Comment by skuppens** [comment]
Hi,

I did manage to get it working.
I had to change the pins as you mentioned and also
This line: i2c = I2C(2, pins=('P10','P11'))

This way I got the values… at this point still strange CO2: around 420 ppm and TVOC around 5 ppb

I’m going to integrate this with the LoRa example.

Stijn

Van: Patrick Müller <notifications@github.com>
Verzonden: woensdag 22 april 2020 17:58
Aan: Notthemarsian/CCS811 <CCS811@noreply.github.com>
CC: Kuppens Stijn <stijn.kuppens@kdg.be>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Notthemarsian/CCS811] Problems running on FiPy from Pycom (#2)

Hi,
I haven’t tried a pycom board but nice that someone uses my little library:

the program aborts at line 12, which initialises the I2C bus:

12 i2c = I2C(scl=Pin(5), sda=Pin(4))

With the message: ValueError: invalid argument(s) value

Now, line 12 is standard micropython syntax and uses the pins 4 and 5.

Looks like pycom has deviated from standard micropython here:
On
https://docs.pycom.io/firmwareapi/pycom/machine/i2c/

I find the following syntax, which is slightly different:


i2c = I2C(0, I2C.MASTER)

Try this. If you get more errors I’m afraid you will have to check each
time if there is a difference in syntax between pycom and standard
micropython.

I wasn’t really happy with my sensor in the end. It seemed to work for a
while, then started to drift towards very high readings. I might try a
infrared sensor next but they are more expensive........

Have fun, Patrick

**Comment by Notthemarsian** [comment]
Very good,

400 ppm is normal outdoor conc. Indoors, you might measure more, e.g. 600
ppm depending on ventilation.

My sensor, on the other hand, after 1 hour suddendly drifted up to 1200 ppm
and more......

CCS811 datasheet:
https://cdn-learn.adafruit.com/assets/assets/000/044/636/original/CCS811_DS000459_2-00-1098798.pdf?1501602769


Have fun, Patrick
